### PR TITLE
Require Ruby >= 2.6

### PR DESCRIPTION
**Pull request by Pontus4**
Both Ruby 2.5 and 2.6 have reached EOL, but JRuby 9.3 still requires Ruby 2.6, which is why we have to allow it.

### CODE REVIEW

**Review by roback — APPROVED** [review]

**Review by Chrizpy — APPROVED** [review]

**Comment by Pontus4** [comment]
JRuby 9.3.x is compatible with Ruby 2.6.x, which is why the check fails. I guess we have to lock the Ruby version to `>= 2.6` instead then...

**Comment by Chrizpy** [comment]
> JRuby 9.3.x is compatible with Ruby 2.6.x, which is why the check fails. I guess we have to lock the Ruby version to `>= 2.6` instead then...

Yeah, looking more closely now it seems to me that the latest `JRuby` version only supports Ruby compatibility up to `2.6.x`. 

They have a meta issue [issue](https://github.com/jruby/jruby/issues/6464) since 2020 that collects the efforts for an upcoming `2.7` (maybe also beyond) support. Looks like these changes are coming in into `JRuby-9.4.x.x` That is also why the `jruby-head` in the CI passes, since it uses `jruby 9.4.0.0-SNAPSHOT (3.1.0)` (from CI log).

**Review by Chrizpy — APPROVED** [review]

**Review by roback — APPROVED** [review]
🟢

**Pull request merged**
