### PR TITLE
Switch to logical requires

### PR DESCRIPTION
**Pull request by dentarg**
Avdi in Ruby Tapas 242:

> Setting up a gem to use logical require paths internally is even
> easier. Since RubyGems automatically adds the gem’s lib directories to
> the load path, in that case we don’t need to mess around with the load
> path at all.

### CODE REVIEW

**Comment by dentarg** [comment]
WIP because I didn't look at the specs

**Comment by walro** [comment]
Are we gonna finish this one up?

**Comment by dentarg** [comment]
I hope so :)

**Comment by dentarg** [comment]
> WIP because I didn't look at the specs

Do we need specs?

**Comment by walro** [comment]
> Do we need specs?

Not sure what the original comment was referring to, but I don't think we need specs to ensure we use require properly. I thought it meant remove `require_relative` from specs.

**Comment by walro** [comment]
> I thought it meant remove require_relative from specs.

We don't seem to have any left.

**Comment by dentarg** [comment]
Yeah, the tests we have should be sufficient for this change

**Comment by dentarg** [comment]
Build failed due to network problems in the Travis CI container (time out when fetching gems), restarted

**Pull request merged**
