### PR TITLE
Add a memory profiler task

### PR DESCRIPTION
**Pull request by jage**
Using https://github.com/SamSaffron/memory_profiler

### CODE REVIEW

**Comment by jage** [comment]
Example output:

```
$ bundle exec rake memory_profile:parse | cat | head -n 9
Total allocated: 26032264 bytes (288004 objects)
Total retained:  0 bytes (0 objects)

allocated memory by gem
-----------------------------------
  19092216  addressable-2.6.0
   6004040  public_suffix-3.0.3
    936008  twingly-url/lib
```

**Comment by walro** [comment]
> $ bundle exec rake memory_profile:parse | cat | head -n 9

Curious, why the piping to `cat` in between?

**Comment by jage** [comment]
Ah, just wanted to keep the pipe open a bit longer, I guess there are better ways to do that ... :)

Without it:

```
$ bundle exec rake memory_profile:parse |  head -n 9
Total allocated: 25536256 bytes (286004 objects)
Total retained:  0 bytes (0 objects)

allocated memory by gem
-----------------------------------
  19092216  addressable-2.6.0
   6004040  public_suffix-3.0.3
    440000  twingly-url/lib

rake aborted!
Errno::EPIPE: Broken pipe @ io_writev - <STDOUT>
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:156:in `write'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:156:in `puts'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:156:in `block (2 levels) in dump_strings'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:155:in `each'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:155:in `block in dump_strings'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:153:in `each'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:153:in `dump_strings'
/Users/jage/.gem/ruby/2.6.2/gems/memory_profiler-0.9.13/lib/memory_profiler/results.rb:134:in `pretty_print'
/Users/jage/Source/twingly/twingly-url/profile/profile.rb:41:in `measure'
/Users/jage/Source/twingly/twingly-url/profile/Rakefile:18:in `block (2 levels) in <top (required)>'
/Users/jage/.rubies/ruby-2.6.2/bin/bundle:23:in `load'
/Users/jage/.rubies/ruby-2.6.2/bin/bundle:23:in `<main>'
Tasks: TOP => memory_profile:parse
(See full trace by running task with --trace)
```

**Comment by walro** [comment]
Ah, thanks. (https://superuser.com/a/554896 a good explanation what happens)

**Pull request merged**
